In [35]:
import tensorflow as tf
import numpy as np
for module in tf,np:
    print(module.__name__, module.__version__)

tensorflow 2.0.0
numpy 1.17.4


In [36]:
# tf_constant
a = tf.constant(1)
b = tf.constant([1.,2,3])
c = tf.constant([[1.,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)
print(c)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)


In [37]:
print(c.shape)
print(c.shape[0])

(3, 3)
3


In [38]:
# constant slice
print(c[1:,:])
print(c[:,1:])
print(c[:,1:2])

tf.Tensor(
[[4. 5. 6.]
 [7. 8. 9.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2. 3.]
 [5. 6.]
 [8. 9.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[2.]
 [5.]
 [8.]], shape=(3, 1), dtype=float32)


In [39]:
# const op
print(c + 10)#   - * /
print(c ** 3)

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[  1.   8.  27.]
 [ 64. 125. 216.]
 [343. 512. 729.]], shape=(3, 3), dtype=float32)


In [40]:
# broadcasting
print( b * c )

tf.Tensor(
[[ 1.  4.  9.]
 [ 4. 10. 18.]
 [ 7. 16. 27.]], shape=(3, 3), dtype=float32)


In [41]:
d = tf.constant([[1.,2],[3,4],[5,6]])
print(c @ d)
print(d @ tf.transpose(d))

tf.Tensor(
[[ 22.  28.]
 [ 49.  64.]
 [ 76. 100.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 5. 11. 17.]
 [11. 25. 39.]
 [17. 39. 61.]], shape=(3, 3), dtype=float32)


In [42]:
print(tf.add(c,10))
print(tf.subtract(c,10))
print(tf.multiply(c,10))
print(tf.divide(c,10))
print(tf.square(c,10))
print(tf.sqrt(c,10))
print(tf.pow(c,3))

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-9. -8. -7.]
 [-6. -5. -4.]
 [-3. -2. -1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.99999994 1.4142134  1.7320508 ]
 [1.9999999  2.236068   2.4494896 ]
 [2.6457512  2.8284268  3.        ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[  1.   8.  27.]
 [ 64. 125. 216.]
 [343. 512. 729.]], shape=(3, 3), dtype=float32)


In [43]:
print(c.numpy())
print(np.square(c))
np_data = np.array([[1.,2,3],[4,5,6]])
print(tf.constant(np_data))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]]
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)


In [44]:
# const change?
a1 = tf.constant(1)
b1 = tf.constant(2)
print(a1)
a1 = b1
print(a1)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [45]:
# variable
v = tf.Variable([[1.,2,3],[4,5,6]], name='myVariable')
print(v)
print(v.numpy())
print(v.value())

<tf.Variable 'myVariable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
[[1. 2. 3.]
 [4. 5. 6.]]
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [46]:
# assign
v.assign(2*v)
print(v)
v[1,1].assign(-1)
print(v)
v[1].assign([7,8,9])
print(v)
v.assign_add(2*v) # v.assign(v+2*v)
print(v)
v.assign_sub(2*v)
print(v)

<tf.Variable 'myVariable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>
<tf.Variable 'myVariable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., -1., 12.]], dtype=float32)>
<tf.Variable 'myVariable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 4., 6.],
       [7., 8., 9.]], dtype=float32)>
<tf.Variable 'myVariable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 6., 12., 18.],
       [21., 24., 27.]], dtype=float32)>
<tf.Variable 'myVariable:0' shape=(2, 3) dtype=float32, numpy=
array([[ -6., -12., -18.],
       [-21., -24., -27.]], dtype=float32)>


In [47]:
v.assign(v-0.001)
print(v)

<tf.Variable 'myVariable:0' shape=(2, 3) dtype=float32, numpy=
array([[ -6.001, -12.001, -18.001],
       [-21.001, -24.001, -27.001]], dtype=float32)>


In [48]:
# = assign?
v1 = v
v = v+1
print(v1)
print(v)

<tf.Variable 'myVariable:0' shape=(2, 3) dtype=float32, numpy=
array([[ -6.001, -12.001, -18.001],
       [-21.001, -24.001, -27.001]], dtype=float32)>
tf.Tensor(
[[ -5.001 -11.001 -17.001]
 [-20.001 -23.001 -26.001]], shape=(2, 3), dtype=float32)


In [49]:
v1[1,2].assign(-1)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ -6.001, -12.001, -18.001],
       [-21.001, -24.001,  -1.   ]], dtype=float32)>

In [50]:
# string
s = tf.constant('coffee')
s1 = tf.constant('中国人a')
print(s)
print(s1)

tf.Tensor(b'coffee', shape=(), dtype=string)
tf.Tensor(b'\xe4\xb8\xad\xe5\x9b\xbd\xe4\xba\xbaa', shape=(), dtype=string)


In [51]:
print(tf.strings.length(s))
print(tf.strings.length(s1, unit='UTF8_CHAR'))

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [52]:
s_decode = tf.strings.unicode_decode(s1, 'UTF8')
print(s_decode)

tf.Tensor([20013 22269 20154    97], shape=(4,), dtype=int32)


In [53]:
# string array
s_array = tf.constant(['ipad', 'ios', '电脑'])
print(s_array)
print(tf.strings.length(s_array))
print(tf.strings.unicode_decode(s_array, 'UTF8'))

tf.Tensor([b'ipad' b'ios' b'\xe7\x94\xb5\xe8\x84\x91'], shape=(3,), dtype=string)
tf.Tensor([4 3 6], shape=(3,), dtype=int32)
<tf.RaggedTensor [[105, 112, 97, 100], [105, 111, 115], [30005, 33041]]>


In [54]:
rag = tf.ragged.constant([[11,21],[21,22,23],[],[41,42,43,44]])
print(rag)

<tf.RaggedTensor [[11, 21], [21, 22, 23], [], [41, 42, 43, 44]]>


In [55]:
print(rag.to_tensor())

tf.Tensor(
[[11 21  0  0]
 [21 22 23  0]
 [ 0  0  0  0]
 [41 42 43 44]], shape=(4, 4), dtype=int32)


In [56]:
print(rag.to_sparse())

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [1 0]
 [1 1]
 [1 2]
 [3 0]
 [3 1]
 [3 2]
 [3 3]], shape=(9, 2), dtype=int64), values=tf.Tensor([11 21 21 22 23 41 42 43 44], shape=(9,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))


In [57]:
t_sparse = tf.SparseTensor(indices=[[1,0],[0,1],[2,3]], values=[1.,2,3], dense_shape=[4,4])
print(t_sparse)

SparseTensor(indices=tf.Tensor(
[[1 0]
 [0 1]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))


In [58]:
t2_sparse = tf.sparse.reorder(t_sparse)
print(tf.sparse.to_dense(t2_sparse))

tf.Tensor(
[[0. 2. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 3.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)
